server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabian1998martinez/Ecommerce-Microservice.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t
